flowchart TD
n02@{ shape: rect, label: Rectangle }
n03@{ shape: rounded, label: Rounded rectangle }
n04@{ shape: circ, label: ellipse }
n05@{ shape: rect, label: square }
n06@{ shape: circ, label: circle }
n07@{ shape: rect, label: process }
n08@{ shape: diam, label: diamond }
n09@{ shape: rect, label: parallelogram }
n010@{ shape: rect, label: hexagon }
n011@{ shape: rect, label: triangle }
n012@{ shape: rect, label: cylinder }
n013@{ shape: rect, label: cloud }
n014@{ shape: doc, label: document }
n015@{ shape: rect, label: internal storage }
n016@{ shape: rect, label: step }
n017@{ shape: rect, label: trapezoid }
n018@{ shape: flag, label: tape }
n019@{ shape: rect, label: data storage }
n020@{ shape: rect, label: and }
n021@{ shape: rect, label: manual input }
n022@{ shape: rect, label: loop limit }
n023@{ shape: rect, label: off page }
n024@{ shape: delay, label: delay }
n025@{ shape: rect, label: display }
n026@{ shape: rect, label: datastore }
n027@{ shape: rect, label: or }
n028@{ shape: rect, label: sum }
n029@{ shape: rect, label: sort }
n030@{ shape: hourglass, label: collate }
n031@{ shape: rect, label: card }
n032@{ shape: rounded, label: data }
n033@{ shape: rect, label: database }
n034@{ shape: diam, label: decision }
n035@{ shape: rect, label: direct data }
n036@{ shape: rect, label: extract or measurement }
n037@{ shape: rect, label: manual operation }
n038@{ shape: rect, label: merge or storage }
n039@{ shape: rect, label: multi-document }
n040@{ shape: rect, label: on page }
n041@{ shape: rounded, label: predefined process }
n042@{ shape: rect, label: preparation }
n043@{ shape: rounded, label: process #2 }
n045@{ shape: rect, label: sequential data }
n046@{ shape: rect, label: start }
n047@{ shape: circ, label: start #2 }
n048@{ shape: rect, label: stored data }
n049@{ shape: rect, label: terminator }
n050@{ shape: rect, label: transfer }